
# REM ========================================================================= 
# REM BOOLTST.SH - Testfile for module BOOL.H/C         Feb 1991 Allan Dystrup
# REM   Generates logfile for  unit tests of BOOL
# REM   Ported from MSDOS BOOLTST.BAT to UBUNTU bash    Nov 2024 Allan Dystrup
# REM =========================================================================


echo ============================================================
echo BOOL.TST : Test Logfile generated by BOOLTST.SH
echo ============================================================


echo ------------------------------------------------------------
echo SCANNER - BOOLEAN OPERATORS				

# REM Obs: XOR operator % must be escaped as a batchfile metachar (ie: %%)
echo --------------------
./bool "ape"
echo --------------------
./bool "^ape"
echo --------------------
./bool "^^ape"
echo --------------------
./bool "ape & bee"
echo --------------------
./bool "ape / bee"
echo --------------------
./bool "ape %% bee"
echo --------------------
./bool "^ape %% bee"
echo --------------------
./bool "ape & ^bee"

echo ------------------------------------------------------------ 
echo SCANNER - PARENTHESIS    

echo --------------------
./bool "ape & bee / cow"                    
echo --------------------
./bool "ape & (bee / cow)"                    
echo --------------------
./bool "ape / bee & cow %% dodo & eel"       
echo --------------------
./bool "((ape / bee) & (cow %% dodo)) & eel" 
 

echo ------------------------------------------------------------
echo SCANNER - ESCAPE          

echo --------------------
./bool "ape\&&bee"              
echo --------------------
./bool "ape\\&bee"              
echo --------------------
./bool "ape\\\&bee"             
echo --------------------
./bool "\&ape&bee"             
echo --------------------
./bool "\\\&ape&bee"            
echo --------------------
./bool "ape&bee\\"              
echo --------------------
./bool "ape&bee\\\&"
echo --------------------
./bool "ape&bee\\"
            

echo ------------------------------------------------------------
echo SCANNER - QUOTE

echo --------------------
./bool ":ape&:&  bee"
echo --------------------
./bool "ape&:bee&:\& cow"
echo --------------------
./bool "ape&:bee&:"
echo --------------------
./bool "::ape& bee"
echo --------------------
./bool "ape&::bee"
echo --------------------
./bool "ape& bee::"
echo --------------------
./bool "ape&:bee"
echo --------------------
./bool ":ape & bee"
echo --------------------
./bool "ape & bee:"
echo --------------------
./bool "ape &\:bee\Heeve\:& cow"
echo --------------------
./bool "ape& :bee\\\Heeve: & cow"


echo ------------------------------------------------------------
echo INTERPRETER                
echo --------------------
./bool "a"                       
echo --------------------
./bool "a&b"
echo --------------------
./bool "a\b"
echo --------------------
./bool "a^b"


echo END module BOOLTST.SH
echo ------------------------------------------------------------ 
REM=========================================================================== 
